"""Email notifications via SMTP."""

import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from core.config import Config

logger = logging.getLogger("cerberus.notifications.email")


def send_email(subject: str, body_html: str, to: str = None) -> bool:
    """Send an email notification."""
    if not Config.SMTP_USER or not Config.SMTP_PASS:
        logger.debug("SMTP not configured")
        return False

    to = to or Config.ALERT_EMAIL_TO
    if not to:
        logger.debug("No recipient configured")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[Cerberus] {subject}"
    msg["From"] = Config.SMTP_FROM
    msg["To"] = to

    # Plain text fallback
    plain = body_html.replace("<br>", "\n").replace("</p>", "\n")
    for tag in ("<p>", "<b>", "</b>", "<i>", "</i>", "<h1>", "</h1>", "<h2>", "</h2>", "<h3>", "</h3>"):
        plain = plain.replace(tag, "")

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    try:
        with smtplib.SMTP(Config.SMTP_HOST, Config.SMTP_PORT) as server:
            server.starttls()
            server.login(Config.SMTP_USER, Config.SMTP_PASS)
            server.sendmail(Config.SMTP_FROM, to, msg.as_string())
        logger.info(f"Email sent to {to}: {subject}")
        return True
    except Exception as e:
        logger.error(f"Email failed: {e}")
        return False


def notify_critical_finding(finding: dict, to: str = None) -> bool:
    """Send email for critical findings."""
    html = f"""
    <h2 style="color: #e74c3c;">Critical Security Finding</h2>
    <p><b>Category:</b> {finding.get('category', 'Unknown')}</p>
    <p><b>Title:</b> {finding.get('title', '')}</p>
    <p><b>Description:</b> {finding.get('description', '')}</p>
    <p><b>Remediation:</b> {finding.get('remediation', '')}</p>
    <hr>
    <p style="color: #888;">This alert was generated by Cerberus Security Platform.</p>
    """
    return send_email(f"CRITICAL: {finding.get('title', 'Security Alert')}", html, to)


def notify_scan_summary(target: str, score: int, findings_count: int, to: str = None) -> bool:
    """Send scan summary email."""
    color = "#27ae60" if score >= 80 else "#f39c12" if score >= 60 else "#e74c3c"
    html = f"""
    <h2>Security Scan Complete</h2>
    <p><b>Target:</b> {target}</p>
    <p><b>Security Score:</b> <span style="color: {color}; font-size: 24px;">{score}/100</span></p>
    <p><b>Findings:</b> {findings_count}</p>
    <hr>
    <p>Log in to Cerberus for full details.</p>
    """
    return send_email(f"Scan Complete: {target} (Score: {score})", html, to)
